branches:
  only:
    - master
os: osx
matrix:
  include:
    # Note: The ordering of the environments is optimized so that the complete matrix runs as quickly as possible,
    # while also providing the first results as early as possible.
    # At the moment, build times for each environment are roughly as follows:
    # xcode7.3: 16 minutes
    # xcode8.3: 7 minutes
    # xcode9.2: 7 minutes
    # xcode10.1: 6 minutes
    # https://docs.travis-ci.com/user/reference/osx/#macos-version
    # This data is based on the following build, which should be similar to most builds on the repo:
    # https://travis-ci.org/pybee/rubicon-objc/builds/506412489
    # Currently, Travis allows a maximum of two concurrent Mac builds per owner:
    # https://blog.travis-ci.com/2017-09-22-macos-update
    # With the following order, xcode7.3 will take up the first slot, and at the same time the three other
    # environments use the second slot in sequence. xcode10.1 will finish first and provide some early results - most
    # test failures happen in all environments and will be quickly reported this way.

    # OSX 10.11 El Capitan
    - osx_image: xcode7.3
    # macOS 10.13 High Sierra
    - osx_image: xcode10.1
    # macOS 10.13 Mojave
    - osx_image: xcode10.2
    # macOS 10.12 Sierra
    - osx_image: xcode9.2
    - osx_image: xcode8.3
language: generic
cache:
  directories:
    ~/.pyenv
install:
  # The different Travis environments have different pyenv versions, and not all have the Python versions we need,
  # so we upgrade pyenv to get a consistent setup in all environments.
  - brew update
  - brew outdated pyenv || brew upgrade pyenv
  # The existing pyenv shims from the build cache may no longer be valid, for example if pyenv was upgraded
  # (in which case the paths used in the shims point to an older, no longer installed pyenv version).
  # By rehashing the shims we can be sure that they are always valid again.
  - pyenv rehash
  # pyenv's shims directory is not in the PATH by default.
  - export PATH="$(pyenv root)/shims:${PATH}"
  - pyenv install --skip-existing 3.5.8
  - pyenv global 3.5.8
  - pip install --upgrade pip setuptools tox
  - make -f Makefile
script:
  - export DYLD_LIBRARY_PATH=`pwd`/tests/objc
  - tox -e py35-default
