branches:
  only:
    - master
os: osx
matrix:
  include:
    # macOS 10.13 High Sierra
    - osx_image: xcode10.1
    # macOS 10.14 Mojave
    - osx_image: xcode10.2
language: generic
install:
  - python3 -m pip install --upgrade pip setuptools
  - make -f Makefile
script:
  - DYLD_LIBRARY_PATH=tests/objc python3 setup.py test
