[build-system]
requires = [
    "setuptools >= 46.4.0",
    "wheel >= 0.32.0",
]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
skip_glob = [
    "docs/conf.py",
    "venv*",
    "local",
]

[tool.towncrier]
directory = "changes"
package = "rubicon.objc"
filename = "docs/background/releases.rst"
title_format = "{version} ({project_date})"
template = "changes/template.rst"
