name: Build status
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests
    needs: beefore
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install -e .
    - name: Build test library
      run: |
        make
    - name: Test
      run: |
        DYLD_LIBRARY_PATH=tests/objc python setup.py test
